-- X FITNESS 9.01 · v6 migration (ALREADY APPLIED to project bkfbylntzmrjqgbrxgic on 5 Aug 2026).
-- Kept here as the source of truth / for rebuilding from scratch.
--
-- 1. xf_pool_locked()          — single source of truth for the 09:59 cut-off
-- 2. draw_results.claimed_at   — prize collection tracking
-- 3. xf_register / xf_claim_social / xf_claim_repost — hard-blocked once the pool locks
-- 4. xf_me                     — now returns prize.claimed / claimed_at and a top-level 'locked'
-- 5. xf_admin_verify_scan      — read-only identity + prize lookup for prize-claim day
-- 6. xf_admin_mark_claimed     — mark collected / undo (UPDATE always carries a WHERE: safeupdate)
-- 7. xf_admin_winners          — full winner roster incl. phone + claim status, for board & CSV
--
-- NOTE on safeupdate: the `authenticator` role preloads it, so any full-table DELETE inside an
-- RPC must be written `delete from t where true;`. It cannot be reproduced in the SQL editor.
